Add docs for citus_schema_move
citusdata/citus_docs pull request #1118
Opened 2024-03-18 08:38 UTC by onurctirtir

2024-03-20 15:26 UTC, JelteF requested changes

2024-03-20 15:26 UTC, JelteF commented on develop/api_udf.rst
> +$$$$$$$$$$$$$$$$$$$$$$$$$
nit: let's make the underline as long as the name

```suggestion
citus_schema_move
$$$$$$$$$$$$$$$$$
```

2024-03-20 15:26 UTC, JelteF commented on develop/api_udf.rst
> +**********
```suggestion
Arguments
*********
```

2024-03-20 15:26 UTC, JelteF commented on develop/api_udf.rst
> +********
```suggestion
Example
*******
```

2024-03-20 15:26 UTC, JelteF commented on develop/api_udf.rst
> +    SELECT citus_schema_move('schema-name'::regnamespace;, 'from_host', 5432, 'to_host', 5432);
```suggestion
    SELECT citus_schema_move('schema-name', 'to_host', 5432);
```

2024-03-20 15:26 UTC, JelteF commented on develop/api_udf.rst
> +**schema_id:** Oid of the distributed schema to be moved.
```suggestion
**schema_id:** Oid of the distributed schema to be moved. If you provide the name of the schema this as a string literal, this string is automatically casted to the oid.
```

2024-03-22 12:30 UTC, onurctirtir commented on develop/api_udf.rst
> +**schema_id:** Oid of the distributed schema to be moved.
```suggestion
**schema_id:** Oid of the distributed schema to be moved. If you provide the name of the schema as a string literal, this string is automatically casted to the oid.
```

2024-04-08 14:44 UTC, JelteF approved these changes

2024-04-08 14:45 UTC, merged