Fix the workaround given for local/dist table joins
citusdata/citus_docs pull request #983
Opened 2021-02-17 12:46 UTC by onurctirtir

Fixes #978

2021-02-17 12:47 UTC, onurctirtir commented on develop/reference_workarounds.rst
> +This error no longer occurs in the current version of Citus unless `citus.local_table_join_policy` GUC is set to `never`.
We should give a reference to the usage of this GUC after we add document it (cc: @SaitTalhaNisanci)

2021-02-17 12:48 UTC, onurctirtir commented on develop/reference_workarounds.rst
> -  JOIN dist USING (id);
Just removed that subquery hint since setting the guc back to `auto` should already be sufficient, any ideas ?

2021-02-24 15:53 UTC, jonels-msft requested changes

2021-02-24 15:53 UTC, jonels-msft commented on develop/reference_workarounds.rst
> +See the reference section for thie GUC for information about its possible
Please add a reference section for the GUC, and provide a link here.

2021-03-03 02:36 UTC, merged

2021-03-03 11:02 UTC, onurctirtir commented
Thanks for merging @jonels-msft :)