Add doc for citus.local_table_join_policy
citusdata/citus_docs pull request #985
Opened 2021-02-25 11:03 UTC by SaitTalhaNisanci

Add doc for citus.local_table_join_policy

2021-02-25 11:16 UTC, onderkalaci commented on develop/api_guc.rst
> +Sets how citus should plan local and distributed table joins. There are four modes available:
should we very briefly mention why would anyone need to change this? Also, maybe move `auto` to top as that's the default?

2021-02-27 03:03 UTC, jonels-msft requested changes
More explanation of the terminology would be helpful. Especially the mechanics of conversion. I wasn't sure if that refers to rewriting the query in some way, or making some kind of temporary copy of tables across nodes...

2021-02-27 03:09 UTC, jonels-msft commented on develop/api_guc.rst
> +citus.local_table_join_policy (enum)
We should add a link target above this, like:

```rst
.. _local_table_join_policy:
```

That way Onur can link to it from https://github.com/citusdata/citus_docs/pull/983

2021-03-02 17:45 UTC, jonels-msft commented
@SaitTalhaNisanci thanks for the clarification! I'll make a few edits on this branch and get it merged.

2021-03-02 19:04 UTC, SaitTalhaNisanci commented
@jonels-msft, let me know if there is anything we can clarify more because if that isn't clear to you, it will not be clear to users for sure :)

2021-03-03 01:08 UTC, merged